# Generated by Django 5.1.5 on 2025-01-30 17:21

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('image', models.ImageField(upload_to='project_images/')),
                ('description', models.TextField()),
                ('link', models.URLField()),
                ('type', models.CharField(choices=[('Website', 'Website'), ('Web App', 'Web Application')], default='Website', max_length=50)),
            ],
        ),
    ]
