# Generated by Django 5.1.5 on 2025-01-31 06:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_documents'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Documents',
        ),
    ]
