name: Django CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      max-parallel: 4
      matrix:
        python-version: [3.13.1]

    steps:
    - uses: actions/checkout@v4
    
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v3
      with:
        python-version: ${{ matrix.python-version }}
    
    - name: Install Dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r Portfolio/requirements.txt
    
    - name: Run Django Migrations
      run: |
        python Portfolio/manage.py migrate
    
    - name: Collect Static Files
      run: |
        python Portfolio/manage.py collectstatic --noinput
    
    - name: Set up Git user info
      run: |
        git config --global user.name 'vishwas382'
        git config --global user.email 'vishwas.bhangare02@gmail.com'
    
    - name: Deploy to GitHub Pages (Main Branch)
      run: |
        # Ensure the static files are copied to the root or /docs folder
        mkdir -p docs
        cp -r Portfolio/staticfiles/* docs/
        cd docs
        git init
        git add .
        git commit -m "Deploy to GitHub Pages"
        git remote add origin https://github.com/${{ github.repository }}.git
        git push -f origin master:gh-pages

